### ISSUE TITLE
MovieAdapter.OnClickListener interface method is not right

### ISSUE THREAD

**Issue by Lekky71** [corneliuze/Movies-Guide#1]
- [x] Make the onClick method have a Movie object parameter.
Hence, 
- [x] change all implementation of the onClick method in classes the interface was implemented.

- [x] change location of `onClickListener.onClick(currentMovie);` in MovieAdapter class.

**Comment by falayy** [comment]
thanks, I'll get to it asap

**Comment by falayy** [comment]
i have passed the movie object as a parameter in the onclick, i have changed the implementation from onCreateViewHolder to onBindViewHolder in movieListAdapter.java
